apiVersion: apps/v1
kind: Deployment
metadata:
  name: reyad-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reyad-react-app
  template:
    metadata:
      labels:
        app: reyad-react-app
    spec:
      containers:
        - name: reyad-react-app
          image: reyad-react-app
          ports:
            - containerPort: 80
